Workflow
nyolarraklay/social-media-client-CA-workflow pull request #9
Opened 2023-11-06 12:21 UTC by nyolarraklay

2023-11-06 19:01 UTC, nyolarraklay commented
In this repository, unit testing is configured with jest and end to end testing is configured with cypress.
cypress did not run succesfully because there is one test that failed because the project did not show user error messages.

2023-11-16 09:48 UTC, Fermain requested changes
Just one change, which is the target URL for cypress. Otherwise a good quality submission!

2023-11-16 09:48 UTC, Fermain commented on cypress/e2e/3-testing/workflow-ca.cy.js
> +    cy.visit("https://nyolarraklay.github.io/social-media-client-CA-workflow");
Its important to test the specific code in the current repo, not a hosted version. This may give a false positive if something is broken in the code.

2023-11-16 09:48 UTC, Fermain commented on cypress/e2e/3-testing/workflow-ca.cy.js
> +      cy.wait(1000);
It would be easier to check localStorage and see if the token is gone

2023-11-16 12:47 UTC, merged